contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #phylomarkercheck channel"
    url: https://nfcore.slack.com/channels/phylomarkercheck
    about: Discussion about the nf-core/phylomarkercheck pipeline
